### ISSUE TITLE
Unrecognized import path

### ISSUE THREAD

**Issue by williamxdavis** [andyleap/go-ssb#13]
With commit 70:

` unrecognized import path "cryptoscope.co/go/secretstream/secrethandshake" `

I reverted the imports but the build still fails because 

```
package github.com/andyleap/go-ssb/cmd/gopub
	imports github.com/cryptix/secretstream: code in directory /Users/mrx/go/src/github.com/cryptix/secretstream expects import "cryptoscope.co/go/secretstream"
```

**Comment by andyleap** [comment]
That's because you reverted the commit that fixed the issue.  Pull and run `go get`.  One of the dependencies (github.com/cryptix/secretstream) was moved to cryptoscope.co/go/secretstream.

**Comment by williamxdavis** [comment]
That gives me this error:

package cryptoscope.co/go/secretstream/secrethandshake: unrecognized import path "cryptoscope.co/go/secretstream/secrethandshake" (https fetch: Get https://cryptoscope.co/go/secretstream/secrethandshake?go-get=1: remote error: tls: internal error)

**Comment by williamxdavis** [comment]
There's some kind of tls issue preventing access to that dep
