### ISSUE TITLE
hash / key deviation

### ISSUE THREAD

**Issue by cryptix** [andyleap/go-ssb#14]
The [fixed order](https://github.com/andyleap/go-ssb/blob/master/message.go#L20) in which the fields of a message are parsed and verified does not work. This is also explained in the [protocol guide](https://ssbc.github.io/scuttlebutt-protocol-guide/#message-format).

It leads to invalid signatures (false negative) and changed hashes of messages. This means replying to _other_ threads and posting of messages that JS clients can't respond to.

I wrote more about it and a saner approach to this problem on this thread on ssb: `%M/qtHwvL1qgbQNZUowOnggGXAtgKuagjQMHGgreuETE=.sha256` ([gateway viewer link](https://viewer.diefreien.club/%25M%2FqtHwvL1qgbQNZUowOnggGXAtgKuagjQMHGgreuETE%3D.sha256))

**Comment by andyleap** [comment]
Yeap, known about that for a long time now, and frankly, I don't give a shit.  SSB needs to get it's act together and stop violating best practices for cryptographic message signing...
